# Generated by Django 5.1.6 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidencematrixrun',
            new_name='evidence_ma_workspa_5823a4_idx',
            old_name='evidence_ma_workspa_7ce624_idx',
        ),
        migrations.RenameIndex(
            model_name='evidencematrixrun',
            new_name='evidence_ma_source__01d4d3_idx',
            old_name='evidence_ma_source__fc45d2_idx',
        ),
    ]
