# Generated by Django 6.0.2 on 2026-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_matrix", "0003_summary_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencematrixrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
