# Generated by Django 6.0.2 on 2026-03-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_matrix", "0005_stage8_matrix_run_inputs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="evidencematrixrun",
            new_name="evidence_ma_workspa_d5d355_idx",
            old_name="evidence_ma_workspa_a8ddce_idx",
        ),
    ]
