# Generated by Django 6.0.2 on 2026-04-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        (
            "evidence_matrix",
            "0006_rename_evidence_ma_workspa_a8ddce_idx_evidence_ma_workspa_d5d355_idx",
        ),
        ("org_context", "0020_planning_context"),
        ("skill_blueprint", "0009_skillblueprintrun_roadmap_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencematrixrun",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this matrix is scoped to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_matrix_runs",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencematrixrun",
            index=models.Index(
                fields=["workspace", "planning_context"],
                name="evidence_ma_workspa_7f81e4_idx",
            ),
        ),
    ]
