# Generated by Django 5.1.6 on 2026-03-19 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intake', '0001_initial'),
        ('media_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source_kind', models.CharField(choices=[('strategy', 'Strategy'), ('roadmap', 'Roadmap'), ('job_description', 'Job description'), ('existing_matrix', 'Existing matrix'), ('org_csv', 'Organization CSV'), ('employee_cv', 'Employee CV'), ('other', 'Other')], max_length=32)),
                ('transport', models.CharField(choices=[('media_file', 'Uploaded media file'), ('inline_text', 'Inline text'), ('external_url', 'External URL')], max_length=32)),
                ('external_url', models.URLField(blank=True, default='')),
                ('inline_text', models.TextField(blank=True, default='')),
                ('language_code', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('attached', 'Attached'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='attached', max_length=16)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('parse_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='intakeworkspace',
            new_name='company_int_slug_ae50ea_idx',
            old_name='company_inta_slug_b6da4e_idx',
        ),
        migrations.RenameIndex(
            model_name='intakeworkspace',
            new_name='company_int_status_a43e83_idx',
            old_name='company_inta_status_2ba87d_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcedocument',
            new_name='company_int_workspa_01bb11_idx',
            old_name='company_inta_workspa_0f4f02_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcedocument',
            new_name='company_int_workspa_a960c6_idx',
            old_name='company_inta_workspa_6f2664_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcedocument',
            new_name='company_int_status_ff6905_idx',
            old_name='company_inta_status_a4fe9f_idx',
        ),
        migrations.AddField(
            model_name='workspacesource',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_sources', to='media_storage.mediafile'),
        ),
        migrations.AddField(
            model_name='workspacesource',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='company_intake.intakeworkspace'),
        ),
        migrations.AddIndex(
            model_name='workspacesource',
            index=models.Index(fields=['workspace', 'source_kind'], name='company_int_workspa_cb3cad_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesource',
            index=models.Index(fields=['workspace', 'status'], name='company_int_workspa_6562e1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacesource',
            index=models.Index(fields=['transport', 'status'], name='company_int_transpo_60e296_idx'),
        ),
    ]
