# Generated by Django 5.1.6 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intake', '0004_workspacesource_parsing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesource',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
