# Generated by Django 6.0.2 on 2026-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0005_workspacesource_archived_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacesource",
            name="status",
            field=models.CharField(
                choices=[
                    ("attached", "Attached"),
                    ("parsing", "Parsing"),
                    ("parsed", "Parsed"),
                    ("failed", "Failed"),
                    ("archived", "Archived"),
                ],
                default="attached",
                max_length=16,
            ),
        ),
    ]
