# Generated by Django 6.0.2 on 2026-04-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0007_intakeworkspace_operator_token"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakeworkspace",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this workspace belongs to. Null for legacy or unlinked workspaces.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="organization.organization",
            ),
        ),
    ]
