# Generated by Django 5.1.6 on 2026-03-19 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='Size in bytes')),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('document', 'Document (PDF)'), ('word', 'Word Document'), ('text', 'Text File'), ('spreadsheet', 'Spreadsheet / CSV')], max_length=32)),
                ('persistent_key', models.CharField(blank=True, help_text='Object key in persistent storage (S3 / MinIO-persistent).', max_length=1024, null=True, unique=True)),
                ('processing_key', models.CharField(blank=True, help_text='Object key in processing storage (MinIO). Null when cleaned up.', max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('uploaded', 'Uploaded to storage'), ('processing', 'Being processed'), ('ready', 'Ready (processing complete)'), ('failed', 'Upload or processing failed')], default='pending', max_length=16)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('processing_description', models.TextField(blank=True, default='', help_text='Textual summary of processing results, editable by user')),
                ('processing_metadata', models.JSONField(blank=True, default=dict, help_text='Structured processing output: page count, dimensions, etc.')),
                ('discussion', models.ForeignKey(blank=True, help_text='If set, access is scoped to discussion members. Null = org-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='feature.discussion')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='organization.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFileVariant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_type', models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('preview', 'Preview'), ('optimized', 'Optimized')], max_length=32)),
                ('content_type', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('persistent_key', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('processing_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra info: compression ratio, page number, etc.')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media_storage.mediafile')),
            ],
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['organization', 'status'], name='media_stora_organiz_e5ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['organization', 'file_category'], name='media_stora_organiz_590644_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['organization', '-created_at'], name='media_stora_organiz_a09854_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['discussion', 'status'], name='media_stora_discuss_64db45_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(condition=models.Q(('persistent_key__isnull', True), ('processing_key__isnull', True), _negated=True), name='media_file_at_least_one_key'),
        ),
        migrations.AddIndex(
            model_name='mediafilevariant',
            index=models.Index(fields=['source_file', 'variant_type'], name='media_stora_source__84c55a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafilevariant',
            unique_together={('source_file', 'variant_type')},
        ),
    ]
