# Generated by Django 5.1.6 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


def backfill_prototype_workspace(apps, schema_editor):
    MediaFile = apps.get_model('media_storage', 'MediaFile')
    WorkspaceSource = apps.get_model('company_intake', 'WorkspaceSource')
    db_alias = schema_editor.connection.alias

    workspace_ids_by_media: dict[int, set[int]] = {}
    for media_file_id, workspace_id in WorkspaceSource.objects.using(db_alias).exclude(
        media_file_id__isnull=True
    ).values_list('media_file_id', 'workspace_id'):
        workspace_ids_by_media.setdefault(media_file_id, set()).add(workspace_id)

    for media_file_id, workspace_ids in workspace_ids_by_media.items():
        if len(workspace_ids) != 1:
            continue
        MediaFile.objects.using(db_alias).filter(
            pk=media_file_id,
            prototype_workspace_id__isnull=True,
            organization_id__isnull=True,
            discussion_id__isnull=True,
        ).update(prototype_workspace_id=next(iter(workspace_ids)))


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('company_intake', '0004_workspacesource_parsing_status'),
        ('media_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='prototype_workspace',
            field=models.ForeignKey(
                blank=True,
                help_text='Workspace owner for prototype uploads and generated artifacts.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='prototype_media_files',
                to='company_intake.intakeworkspace',
            ),
        ),
        migrations.RunPython(backfill_prototype_workspace, noop_reverse),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['prototype_workspace', 'status'], name='media_stora_prototy_ee9afd_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['prototype_workspace', '-created_at'], name='media_stora_prototy_698d75_idx'),
        ),
    ]
