# Generated by Django 6.0.2 on 2026-03-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_storage", "0002_mediafile_prototype_workspace"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mediafile",
            new_name="media_stora_prototy_84cd0b_idx",
            old_name="media_stora_prototy_ee9afd_idx",
        ),
        migrations.RenameIndex(
            model_name="mediafile",
            new_name="media_stora_prototy_44f0f3_idx",
            old_name="media_stora_prototy_698d75_idx",
        ),
    ]
