# Generated by Django 6.0.2 on 2026-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_storage", "0004_add_single_scope_constraint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mediafile",
            new_name="media_stora_prototy_cdce50_idx",
            old_name="media_stora_prototy_filcat_idx",
        ),
    ]
