# Generated by Django 5.1.6 on 2026-03-19 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_intake', '0002_workspacesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_employee_id', models.CharField(blank=True, default='', max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('current_title', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_kind', models.CharField(choices=[('department', 'Department'), ('functional_team', 'Functional team'), ('product_team', 'Product team'), ('other', 'Other')], default='department', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrgAssignment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_kind', models.CharField(choices=[('home', 'Home department'), ('functional', 'Functional'), ('product', 'Product'), ('other', 'Other')], default='home', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('title_override', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignments', to='org_context.employee')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_org_assignments', to='company_intake.workspacesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_org_assignments', to='company_intake.intakeworkspace')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='org_context.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedSource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parser_name', models.CharField(default='prototype-v1', max_length=64)),
                ('parser_version', models.CharField(default='1.0', max_length=32)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_source', to='company_intake.workspacesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_sources', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProjectAssignment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, default='', max_length=255)),
                ('allocation_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='org_context.employee')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_project_assignments', to='company_intake.workspacesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_project_assignments', to='company_intake.intakeworkspace')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='org_context.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports_links', to='org_context.employee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers_links', to='org_context.employee')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_lines', to='company_intake.workspacesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_lines', to='company_intake.intakeworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, default='', max_length=255)),
                ('seniority', models.CharField(blank=True, default='', max_length=64)),
                ('canonical_occupation_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_profiles', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OccupationMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation_key', models.CharField(max_length=255)),
                ('occupation_name_en', models.CharField(max_length=255)),
                ('occupation_name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_mappings', to='company_intake.intakeworkspace')),
                ('role_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_mappings', to='org_context.roleprofile')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_key', models.CharField(max_length=255)),
                ('display_name_en', models.CharField(max_length=255)),
                ('display_name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='company_intake.intakeworkspace')),
            ],
            options={
                'ordering': ['display_name_en'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkillRequirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_level', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('source_kind', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('role_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='org_context.roleprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skill_requirements', to='company_intake.intakeworkspace')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='org_context.skill')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkillEvidence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(max_length=64)),
                ('current_level', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='org_context.employee')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_evidence', to='company_intake.workspacesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skill_evidence', to='company_intake.intakeworkspace')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_evidence', to='org_context.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=255)),
                ('language_code', models.CharField(blank=True, default='', max_length=16)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='org_context.skill')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parsed_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='org_context.parsedsource')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['workspace', 'full_name'], name='org_context_workspa_55ef1d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['workspace', 'external_employee_id'], name='org_context_workspa_aba56c_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['workspace', 'unit_kind'], name='org_context_workspa_6bc29a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgunit',
            unique_together={('workspace', 'name', 'unit_kind')},
        ),
        migrations.AddIndex(
            model_name='employeeorgassignment',
            index=models.Index(fields=['workspace', 'assignment_kind'], name='org_context_workspa_7167ea_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeorgassignment',
            index=models.Index(fields=['workspace', 'employee'], name='org_context_workspa_542ee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeorgassignment',
            unique_together={('employee', 'org_unit', 'assignment_kind')},
        ),
        migrations.AddIndex(
            model_name='parsedsource',
            index=models.Index(fields=['workspace', '-updated_at'], name='org_context_workspa_cb3c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'name'], name='org_context_workspa_f48b64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='employeeprojectassignment',
            index=models.Index(fields=['workspace', 'employee'], name='org_context_workspa_e74edb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprojectassignment',
            index=models.Index(fields=['workspace', 'project'], name='org_context_workspa_e76d8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprojectassignment',
            unique_together={('employee', 'project', 'role_label')},
        ),
        migrations.AddIndex(
            model_name='reportingline',
            index=models.Index(fields=['workspace', 'manager'], name='org_context_workspa_a3e7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingline',
            index=models.Index(fields=['workspace', 'report'], name='org_context_workspa_f8ae67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingline',
            unique_together={('workspace', 'manager', 'report')},
        ),
        migrations.AddIndex(
            model_name='roleprofile',
            index=models.Index(fields=['workspace', 'family'], name='org_context_workspa_c70646_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleprofile',
            unique_together={('workspace', 'name', 'seniority')},
        ),
        migrations.AddIndex(
            model_name='occupationmapping',
            index=models.Index(fields=['workspace', 'occupation_key'], name='org_context_workspa_733ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['canonical_key'], name='org_context_canonic_5ed95a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('workspace', 'canonical_key')},
        ),
        migrations.AddIndex(
            model_name='roleskillrequirement',
            index=models.Index(fields=['workspace', 'target_level'], name='org_context_workspa_efcf3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleskillrequirement',
            unique_together={('role_profile', 'skill')},
        ),
        migrations.AddIndex(
            model_name='employeeskillevidence',
            index=models.Index(fields=['workspace', 'employee'], name='org_context_workspa_407245_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeskillevidence',
            index=models.Index(fields=['workspace', 'skill'], name='org_context_workspa_139e49_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeskillevidence',
            index=models.Index(fields=['source_kind'], name='org_context_source__67214a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillalias',
            index=models.Index(fields=['alias'], name='org_context_alias_e7f17f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillalias',
            unique_together={('skill', 'alias', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='sourcechunk',
            index=models.Index(fields=['parsed_source', 'chunk_index'], name='org_context_parsed__2434df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcechunk',
            unique_together={('parsed_source', 'chunk_index')},
        ),
    ]
