# Generated by Django 6.0.2 on 2026-03-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0002_employeerolematch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeerolematch",
            new_name="org_context_workspa_e38ed5_idx",
            old_name="org_context_worksp_5a7f6e_idx",
        ),
        migrations.RenameIndex(
            model_name="employeerolematch",
            new_name="org_context_workspa_f716a5_idx",
            old_name="org_context_worksp_30f521_idx",
        ),
        migrations.RenameIndex(
            model_name="employeerolematch",
            new_name="org_context_workspa_6f1099_idx",
            old_name="org_context_worksp_171efe_idx",
        ),
    ]
