# Generated by Django 6.0.2 on 2026-03-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0006_roleprofile_conditional_uniqueness"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="roleprofile",
            new_name="org_context_workspa_a1b2b3_idx",
            old_name="org_context_workspa_1c7cc3_idx",
        ),
    ]
