# Generated by Django 6.0.2 on 2026-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0008_employeecvprofile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeecvprofile",
            new_name="org_context_workspa_686562_idx",
            old_name="org_context_workspa_65c7d8_idx",
        ),
        migrations.RenameIndex(
            model_name="employeecvprofile",
            new_name="org_context_workspa_dd04c3_idx",
            old_name="org_context_workspa_d82df2_idx",
        ),
        migrations.RenameIndex(
            model_name="employeecvprofile",
            new_name="org_context_workspa_17416c_idx",
            old_name="org_context_workspa_2984f0_idx",
        ),
        migrations.RenameIndex(
            model_name="employeecvprofile",
            new_name="org_context_workspa_c5c083_idx",
            old_name="org_context_workspa_3b0b42_idx",
        ),
    ]
