# Generated by Django 6.0.2 on 2026-03-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0010_employeecvmatchcandidate"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeecvmatchcandidate",
            new_name="org_context_workspa_dddf27_idx",
            old_name="org_context_workspa_6f4f0d_idx",
        ),
        migrations.RenameIndex(
            model_name="employeecvmatchcandidate",
            new_name="org_context_workspa_31ba3b_idx",
            old_name="org_context_workspa_44d047_idx",
        ),
    ]
