# Generated by Django 6.0.2 on 2026-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0012_evidence_lineage_fks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeeskillevidence",
            new_name="org_context_workspa_2d6fbd_idx",
            old_name="org_context_evidence_cycle_idx",
        ),
    ]
