# Generated by Django 6.0.2 on 2026-03-26 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "org_context",
            "0013_rename_org_context_evidence_cycle_idx_org_context_workspa_2d6fbd_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EscoConceptScheme",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept_type",
                    models.CharField(
                        blank=True, default="ConceptScheme", max_length=64
                    ),
                ),
                ("concept_scheme_uri", models.URLField(max_length=1024, unique=True)),
                (
                    "preferred_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("has_top_concept", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["preferred_label", "title"],
            },
        ),
        migrations.CreateModel(
            name="EscoDictionaryEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=64)),
                (
                    "data_header",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "property_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["filename", "data_header"],
                "unique_together": {("filename", "data_header", "property_name")},
            },
        ),
        migrations.CreateModel(
            name="EscoImportRun",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dataset_version", models.CharField(default="v1.2.1", max_length=64)),
                ("language_code", models.CharField(default="en", max_length=16)),
                ("dataset_path", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_version", "language_code"],
                        name="org_context_dataset_bdb2f4_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="org_context_status_fd1c7d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EscoIscoGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="ISCOGroup", max_length=64),
                ),
                ("concept_uri", models.URLField(max_length=1024, unique=True)),
                ("code", models.CharField(blank=True, default="", max_length=32)),
                ("preferred_label", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("in_scheme", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["code", "preferred_label"],
                "indexes": [
                    models.Index(fields=["code"], name="org_context_code_745672_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EscoOccupation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept_uri", models.URLField(max_length=1024, unique=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="Occupation", max_length=64),
                ),
                ("isco_group", models.CharField(blank=True, default="", max_length=64)),
                ("preferred_label", models.CharField(max_length=512)),
                (
                    "normalized_preferred_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
                ("regulated_profession_note", models.TextField(blank=True, default="")),
                ("scope_note", models.TextField(blank=True, default="")),
                ("definition", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("in_scheme", models.JSONField(blank=True, default=list)),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("nace_code", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["preferred_label"],
                "indexes": [
                    models.Index(
                        fields=["normalized_preferred_label"],
                        name="org_context_normali_857f39_idx",
                    ),
                    models.Index(
                        fields=["isco_group"], name="org_context_isco_gr_cd401a_idx"
                    ),
                    models.Index(fields=["code"], name="org_context_code_cbaec9_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="occupationmapping",
            name="esco_occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_mappings",
                to="org_context.escooccupation",
            ),
        ),
        migrations.CreateModel(
            name="EscoSkill",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept_uri", models.URLField(max_length=1024, unique=True)),
                (
                    "concept_type",
                    models.CharField(
                        blank=True, default="KnowledgeSkillCompetence", max_length=64
                    ),
                ),
                ("skill_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "reuse_level",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("preferred_label", models.CharField(max_length=512)),
                (
                    "normalized_preferred_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
                ("scope_note", models.TextField(blank=True, default="")),
                ("definition", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("in_scheme", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["preferred_label"],
                "indexes": [
                    models.Index(
                        fields=["normalized_preferred_label"],
                        name="org_context_normali_403fb6_idx",
                    ),
                    models.Index(
                        fields=["skill_type"], name="org_context_skill_t_0f0755_idx"
                    ),
                    models.Index(
                        fields=["status"], name="org_context_status_df84f9_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="esco_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_skills",
                to="org_context.escoskill",
            ),
        ),
        migrations.CreateModel(
            name="EscoSkillGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept_uri", models.URLField(max_length=1024, unique=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="SkillGroup", max_length=64),
                ),
                ("preferred_label", models.CharField(max_length=512)),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
                ("scope_note", models.TextField(blank=True, default="")),
                ("in_scheme", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, default="")),
                ("code", models.CharField(blank=True, default="", max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["preferred_label"],
                "indexes": [
                    models.Index(fields=["code"], name="org_context_code_47a170_idx"),
                    models.Index(
                        fields=["preferred_label"],
                        name="org_context_preferr_ad69f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EscoSkillHierarchyPath",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level_0_uri",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                (
                    "level_0_preferred_term",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "level_1_uri",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                (
                    "level_1_preferred_term",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "level_2_uri",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                (
                    "level_2_preferred_term",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "level_3_uri",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                (
                    "level_3_preferred_term",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("scope_note", models.TextField(blank=True, default="")),
                (
                    "level_0_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "level_1_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "level_2_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "level_3_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "ordering": [
                    "level_0_code",
                    "level_1_code",
                    "level_2_code",
                    "level_3_code",
                ],
                "indexes": [
                    models.Index(
                        fields=["level_3_uri"], name="org_context_level_3_53f764_idx"
                    ),
                    models.Index(
                        fields=["level_2_uri"], name="org_context_level_2_3e57ab_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EscoGreenOccupationShare",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("concept_uri", models.URLField(max_length=1024)),
                ("code", models.CharField(blank=True, default="", max_length=32)),
                ("preferred_label", models.CharField(max_length=255)),
                (
                    "green_share",
                    models.DecimalField(decimal_places=16, default=0, max_digits=18),
                ),
                (
                    "isco_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="green_share_rows",
                        to="org_context.escoiscogroup",
                    ),
                ),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="green_share_rows",
                        to="org_context.escooccupation",
                    ),
                ),
            ],
            options={
                "ordering": ["-green_share", "preferred_label"],
                "indexes": [
                    models.Index(fields=["code"], name="org_context_code_c90961_idx")
                ],
                "unique_together": {("concept_uri", "code")},
            },
        ),
        migrations.CreateModel(
            name="EscoOccupationBroaderRelation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("concept_uri", models.URLField(max_length=1024)),
                (
                    "concept_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "broader_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("broader_uri", models.URLField(max_length=1024)),
                (
                    "broader_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "broader_occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_relations",
                        to="org_context.escooccupation",
                    ),
                ),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broader_relations",
                        to="org_context.escooccupation",
                    ),
                ),
            ],
            options={
                "ordering": ["concept_label", "broader_label"],
                "indexes": [
                    models.Index(
                        fields=["concept_uri"], name="org_context_concept_d639ff_idx"
                    ),
                    models.Index(
                        fields=["broader_uri"], name="org_context_broader_1f301e_idx"
                    ),
                ],
                "unique_together": {("concept_uri", "broader_uri")},
            },
        ),
        migrations.CreateModel(
            name="EscoOccupationCollectionMembership",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collection_key", models.CharField(max_length=64)),
                (
                    "collection_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("broader_concept_uris", models.JSONField(blank=True, default=list)),
                ("broader_concept_labels", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="org_context.escooccupation",
                    ),
                ),
            ],
            options={
                "ordering": ["collection_key", "esco_occupation_id"],
                "indexes": [
                    models.Index(
                        fields=["collection_key"], name="org_context_collect_26441b_idx"
                    )
                ],
                "unique_together": {("esco_occupation", "collection_key")},
            },
        ),
        migrations.CreateModel(
            name="EscoOccupationLabel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=512)),
                (
                    "normalized_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "label_kind",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("alt", "Alternative"),
                            ("hidden", "Hidden"),
                        ],
                        default="alt",
                        max_length=32,
                    ),
                ),
                ("language_code", models.CharField(default="en", max_length=16)),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="org_context.escooccupation",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(
                        fields=["normalized_label"],
                        name="org_context_normali_32c05d_idx",
                    ),
                    models.Index(
                        fields=["label_kind"], name="org_context_label_k_917985_idx"
                    ),
                ],
                "unique_together": {
                    ("esco_occupation", "label_kind", "label", "language_code")
                },
            },
        ),
        migrations.CreateModel(
            name="EscoOccupationSkillRelation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relation_type", models.CharField(max_length=64)),
                ("skill_type", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_relations",
                        to="org_context.escooccupation",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupation_relations",
                        to="org_context.escoskill",
                    ),
                ),
            ],
            options={
                "ordering": ["occupation_id", "relation_type", "skill_id"],
                "indexes": [
                    models.Index(
                        fields=["relation_type"], name="org_context_relatio_ad9a10_idx"
                    ),
                    models.Index(
                        fields=["skill_type"], name="org_context_skill_t_1e45c1_idx"
                    ),
                ],
                "unique_together": {("occupation", "skill", "relation_type")},
            },
        ),
        migrations.CreateModel(
            name="EscoSkillCollectionMembership",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collection_key", models.CharField(max_length=64)),
                (
                    "collection_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("broader_concept_uris", models.JSONField(blank=True, default=list)),
                ("broader_concept_labels", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "esco_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="org_context.escoskill",
                    ),
                ),
            ],
            options={
                "ordering": ["collection_key", "esco_skill_id"],
                "indexes": [
                    models.Index(
                        fields=["collection_key"], name="org_context_collect_973d33_idx"
                    )
                ],
                "unique_together": {("esco_skill", "collection_key")},
            },
        ),
        migrations.CreateModel(
            name="EscoSkillBroaderRelation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("concept_uri", models.URLField(max_length=1024)),
                (
                    "concept_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "broader_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("broader_uri", models.URLField(max_length=1024)),
                (
                    "broader_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "broader_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrower_relations",
                        to="org_context.escoskill",
                    ),
                ),
                (
                    "esco_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broader_relations",
                        to="org_context.escoskill",
                    ),
                ),
                (
                    "broader_skill_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broader_group_relations",
                        to="org_context.escoskillgroup",
                    ),
                ),
                (
                    "esco_skill_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_relations",
                        to="org_context.escoskillgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["concept_label", "broader_label"],
                "indexes": [
                    models.Index(
                        fields=["concept_uri"], name="org_context_concept_743e95_idx"
                    ),
                    models.Index(
                        fields=["broader_uri"], name="org_context_broader_e2549f_idx"
                    ),
                ],
                "unique_together": {("concept_uri", "broader_uri")},
            },
        ),
        migrations.CreateModel(
            name="EscoSkillLabel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=512)),
                (
                    "normalized_label",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "label_kind",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("alt", "Alternative"),
                            ("hidden", "Hidden"),
                        ],
                        default="alt",
                        max_length=32,
                    ),
                ),
                ("language_code", models.CharField(default="en", max_length=16)),
                (
                    "esco_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="org_context.escoskill",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(
                        fields=["normalized_label"],
                        name="org_context_normali_e4fd4f_idx",
                    ),
                    models.Index(
                        fields=["label_kind"], name="org_context_label_k_870be5_idx"
                    ),
                ],
                "unique_together": {
                    ("esco_skill", "label_kind", "label", "language_code")
                },
            },
        ),
        migrations.CreateModel(
            name="EscoSkillRelation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_skill_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("relation_type", models.CharField(max_length=64)),
                (
                    "related_skill_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "original_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_skill_relations",
                        to="org_context.escoskill",
                    ),
                ),
                (
                    "related_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_skill_relations",
                        to="org_context.escoskill",
                    ),
                ),
            ],
            options={
                "ordering": ["relation_type", "original_skill_id"],
                "indexes": [
                    models.Index(
                        fields=["relation_type"], name="org_context_relatio_407d06_idx"
                    )
                ],
                "unique_together": {
                    ("original_skill", "related_skill", "relation_type")
                },
            },
        ),
    ]
