# Generated by Django 6.0.2 on 2026-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "org_context",
            "0014_escoconceptscheme_escodictionaryentry_escoimportrun_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="escogreenoccupationshare",
            name="green_share",
            field=models.DecimalField(decimal_places=20, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name="escooccupation",
            name="nace_code",
            field=models.TextField(blank=True, default=""),
        ),
    ]
