# Generated by Django 6.0.2 on 2026-03-26 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0007_intakeworkspace_operator_token"),
        ("org_context", "0015_alter_escogreenoccupationshare_green_share_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogResolutionReviewItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term_kind",
                    models.CharField(
                        choices=[("skill", "Skill"), ("occupation", "Occupation")],
                        max_length=32,
                    ),
                ),
                ("raw_term", models.CharField(max_length=255)),
                ("normalized_term", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("seen_count", models.PositiveIntegerField(default=1)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_resolution_review_items",
                        to="company_intake.intakeworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["term_kind", "normalized_term"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "term_kind", "normalized_term"],
                        name="org_context_workspa_058c84_idx",
                    ),
                    models.Index(
                        fields=["status", "term_kind"],
                        name="org_context_status_274b1a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", True)),
                        fields=("term_kind", "normalized_term"),
                        name="uq_catalog_review_item_global_term",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", False)),
                        fields=("workspace", "term_kind", "normalized_term"),
                        name="uq_catalog_review_item_workspace_term",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OccupationResolutionOverride",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_term", models.CharField(max_length=255)),
                ("normalized_term", models.CharField(max_length=255)),
                (
                    "occupation_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "occupation_name_en",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="suggested",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_overrides",
                        to="org_context.escooccupation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupation_resolution_overrides",
                        to="company_intake.intakeworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_term", "workspace_id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "normalized_term"],
                        name="org_context_workspa_8527ed_idx",
                    ),
                    models.Index(
                        fields=["status", "normalized_term"],
                        name="org_context_status_37f26d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", True)),
                        fields=("normalized_term",),
                        name="uq_occupation_resolution_override_global_term",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", False)),
                        fields=("workspace", "normalized_term"),
                        name="uq_occupation_resolution_override_workspace_term",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillResolutionOverride",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_term", models.CharField(max_length=255)),
                ("normalized_term", models.CharField(max_length=255)),
                ("canonical_key", models.CharField(max_length=255)),
                ("display_name_en", models.CharField(max_length=255)),
                (
                    "display_name_ru",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="suggested",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "esco_skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_overrides",
                        to="org_context.escoskill",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_resolution_overrides",
                        to="company_intake.intakeworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_term", "workspace_id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "normalized_term"],
                        name="org_context_workspa_4173a5_idx",
                    ),
                    models.Index(
                        fields=["status", "normalized_term"],
                        name="org_context_status_71df43_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", True)),
                        fields=("normalized_term",),
                        name="uq_skill_resolution_override_global_term",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("workspace__isnull", False)),
                        fields=("workspace", "normalized_term"),
                        name="uq_skill_resolution_override_workspace_term",
                    ),
                ],
            },
        ),
    ]
