# Generated by Django 6.0.2 on 2026-04-07 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0007_intakeworkspace_operator_token"),
        ("org_context", "0018_skill_review_and_evidence_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapAnalysisRun",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Roadmap analysis", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "analysis_version",
                    models.CharField(
                        default="roadmap-v1",
                        help_text="Schema version for the structured output fields.",
                        max_length=32,
                    ),
                ),
                (
                    "source_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of which sources were analyzed: UUIDs, titles, kinds, and counts.",
                    ),
                ),
                (
                    "input_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of workspace profile and analysis fingerprint at run time.",
                    ),
                ),
                (
                    "initiatives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured initiatives extracted from roadmap and strategy inputs.",
                    ),
                ),
                (
                    "workstreams",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured delivery workstreams derived from initiatives.",
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cross-workstream dependencies identified during analysis.",
                    ),
                ),
                (
                    "delivery_risks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Delivery risks surfaced from roadmap decomposition.",
                    ),
                ),
                (
                    "capability_bundles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Clustered capability bundles grouped across workstreams.",
                    ),
                ),
                (
                    "prd_summaries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="PRD-style initiative summaries derived from the roadmap.",
                    ),
                ),
                (
                    "clarification_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Roadmap-analysis questions requiring operator clarification.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if the run failed.",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_analyses",
                        to="company_intake.intakeworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="org_context_workspa_6831fb_idx",
                    ),
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="org_context_workspa_15e9b6_idx",
                    ),
                ],
            },
        ),
    ]
