# Generated by Django 6.0.2 on 2026-04-07 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        ("org_context", "0019_roadmapanalysisrun"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningContext",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("org", "Organization baseline"),
                            ("project", "Project"),
                            ("scenario", "Scenario"),
                        ],
                        default="org",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this context belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_contexts",
                        to="organization.organization",
                    ),
                ),
                (
                    "parent_context",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent context for inheritance. Org contexts have no parent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_contexts",
                        to="org_context.planningcontext",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this context is scoped to when kind=project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_contexts",
                        to="org_context.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workspace this context belongs to. Null for org-only contexts.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_contexts",
                        to="company_intake.intakeworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContextProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Company profile fields. Root contexts keep the full profile; child contexts keep overrides.",
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technology stack additions or the full stack for non-inheriting contexts.",
                    ),
                ),
                (
                    "tech_stack_remove",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies removed from the inherited stack for child contexts.",
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Planning constraints such as budget or team-size caps.",
                    ),
                ),
                (
                    "growth_goals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Growth goals relevant to this planning scope.",
                    ),
                ),
                (
                    "inherit_from_parent",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile inherits unoverridden values from its parent context.",
                    ),
                ),
                (
                    "override_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field names that override parent values.",
                    ),
                ),
                (
                    "planning_context",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="org_context.planningcontext",
                    ),
                ),
            ],
            options={
                "ordering": ["planning_context__name"],
            },
        ),
        migrations.CreateModel(
            name="PlanningContextSource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap"),
                            ("strategy", "Strategy"),
                            ("role_reference", "Role reference"),
                            ("org_structure", "Org structure"),
                            ("employee_cv", "Employee CV"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False to exclude an inherited source from this context.",
                    ),
                ),
                (
                    "include_in_blueprint",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this source should be used for blueprint generation.",
                    ),
                ),
                (
                    "include_in_roadmap_analysis",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this source should be used for roadmap analysis.",
                    ),
                ),
                (
                    "inherited_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this source was inherited or shadowed from another context.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inherited_source_links",
                        to="org_context.planningcontext",
                    ),
                ),
                (
                    "planning_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_sources",
                        to="org_context.planningcontext",
                    ),
                ),
                (
                    "workspace_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_context_links",
                        to="company_intake.workspacesource",
                    ),
                ),
            ],
            options={
                "ordering": ["planning_context", "usage_type"],
            },
        ),
        migrations.AddIndex(
            model_name="planningcontext",
            index=models.Index(
                fields=["workspace", "kind"], name="org_context_workspa_07be1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningcontext",
            index=models.Index(
                fields=["organization", "kind"], name="org_context_organiz_a8520d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planningcontext",
            index=models.Index(
                fields=["workspace", "slug"], name="org_context_workspa_fc354d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontext",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", False)),
                fields=("workspace", "slug"),
                name="uq_planning_context_workspace_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontext",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("workspace__isnull", False),
                    ("organization__isnull", False),
                    _connector="OR",
                ),
                name="planning_context_has_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontext",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "org"), ("parent_context__isnull", True)),
                    models.Q(("kind", "org"), _negated=True),
                    _connector="OR",
                ),
                name="planning_context_org_no_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontext",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "project"), ("project__isnull", False)),
                    models.Q(("kind", "project"), _negated=True),
                    _connector="OR",
                ),
                name="planning_context_project_requires_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontext",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "scenario"), ("parent_context__isnull", False)),
                    models.Q(("kind", "scenario"), _negated=True),
                    _connector="OR",
                ),
                name="planning_context_scenario_requires_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="planningcontextsource",
            index=models.Index(
                fields=["planning_context", "usage_type"],
                name="org_context_plannin_9b27cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningcontextsource",
            index=models.Index(
                fields=["planning_context", "is_active"],
                name="org_context_plannin_37dea9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningcontextsource",
            index=models.Index(
                fields=["workspace_source"], name="org_context_workspa_3018b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningcontextsource",
            constraint=models.UniqueConstraint(
                fields=("planning_context", "workspace_source"),
                name="uq_planning_context_source",
            ),
        ),
    ]
