# Generated by Django 6.0.2 on 2026-04-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        ("org_context", "0021_backfill_planning_contexts"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerolematch",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this match was computed for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_role_matches",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddField(
            model_name="roadmapanalysisrun",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this analysis is scoped to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roadmap_analyses",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="employeerolematch",
            index=models.Index(
                fields=["workspace", "planning_context"],
                name="org_context_workspa_376868_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapanalysisrun",
            index=models.Index(
                fields=["workspace", "planning_context", "status"],
                name="org_context_workspa_970179_idx",
            ),
        ),
    ]
