# Generated by Django 6.0.2 on 2026-04-07 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0022_roadmap_and_role_match_planning_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationConstraint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("max_allocation", "Max projects per employee"),
                            ("min_team_size", "Min team size per project"),
                            ("required_backup", "Required skill backup"),
                            ("fixed_assignment", "Fixed employee-project assignment"),
                            ("max_fte", "Max FTE per employee"),
                            ("skill_coverage", "Minimum employees per critical skill"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "constraint_value",
                    models.JSONField(
                        default=dict,
                        help_text="Constraint parameters. Shape depends on constraint_type.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description for why this constraint exists.",
                    ),
                ),
                (
                    "is_hard",
                    models.BooleanField(
                        default=True,
                        help_text="Hard constraints must be satisfied; soft constraints are preferences.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "planning_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_constraints",
                        to="org_context.planningcontext",
                    ),
                ),
            ],
            options={
                "ordering": ["constraint_type"],
                "indexes": [
                    models.Index(
                        fields=["planning_context", "constraint_type"],
                        name="org_context_plannin_de1d96_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCapabilityAvailability",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current skill level on a 1-5 scale.",
                        max_digits=4,
                    ),
                ),
                (
                    "available_fte",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="FTE available for future allocation.",
                        max_digits=4,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High (assessment confirmed)"),
                            ("medium", "Medium (CV evidence)"),
                            ("low", "Low (inferred)"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "existing_allocation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Current allocations reducing availability.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_availabilities",
                        to="org_context.employee",
                    ),
                ),
                (
                    "planning_context",
                    models.ForeignKey(
                        help_text="Planning context that scoped this availability snapshot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_availabilities",
                        to="org_context.planningcontext",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_availabilities",
                        to="org_context.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__full_name", "skill__display_name_en"],
                "indexes": [
                    models.Index(
                        fields=["planning_context", "employee"],
                        name="org_context_plannin_358b99_idx",
                    ),
                    models.Index(
                        fields=["planning_context", "skill"],
                        name="org_context_plannin_dc7569_idx",
                    ),
                    models.Index(
                        fields=["employee", "skill"],
                        name="org_context_employe_bf0826_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("planning_context", "employee", "skill"),
                        name="uq_employee_capability_availability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectCapabilityDemand",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_family",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Associated role family, for example backend_engineer.",
                        max_length=64,
                    ),
                ),
                (
                    "demand_level",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Minimum skill level required on a 1-5 scale.",
                    ),
                ),
                (
                    "fte_demand",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        help_text="Full-time equivalent demand for this capability.",
                        max_digits=4,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Priority 1-5, where 1 is highest."
                    ),
                ),
                (
                    "time_horizon",
                    models.CharField(
                        choices=[
                            ("short", "Short term (0-3 months)"),
                            ("medium", "Medium term (3-6 months)"),
                            ("long", "Long term (6-12 months)"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("roadmap_analysis", "From roadmap analysis"),
                            ("blueprint", "From blueprint"),
                            ("manual", "Manually specified"),
                        ],
                        default="blueprint",
                        max_length=32,
                    ),
                ),
                (
                    "initiative_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to the roadmap initiative driving this demand.",
                        max_length=255,
                    ),
                ),
                (
                    "workstream_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to the workstream driving this demand.",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "planning_context",
                    models.ForeignKey(
                        help_text="Planning context that owns this demand.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_demands",
                        to="org_context.planningcontext",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that needs this capability.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_demands",
                        to="org_context.project",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill or capability needed by the project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_demands",
                        to="org_context.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "role_family"],
                "indexes": [
                    models.Index(
                        fields=["planning_context", "priority"],
                        name="org_context_plannin_829e7e_idx",
                    ),
                    models.Index(
                        fields=["planning_context", "skill"],
                        name="org_context_plannin_f55ee1_idx",
                    ),
                    models.Index(
                        fields=["project", "skill"],
                        name="org_context_project_b65537_idx",
                    ),
                ],
            },
        ),
    ]
