# Generated by Django 5.1.6 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_blueprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skillblueprintrun',
            new_name='skill_bluep_workspa_8429d3_idx',
            old_name='skill_bluep_workspa_558d33_idx',
        ),
    ]
