# Generated by Django 6.0.2 on 2026-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_blueprint", "0003_rolelibrarysnapshot_rolelibraryentry_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rolelibraryentry",
            new_name="skill_bluep_snapsho_f92d1a_idx",
            old_name="skill_bluep_snapsho_11ff02_idx",
        ),
        migrations.RenameIndex(
            model_name="rolelibraryentry",
            new_name="skill_bluep_snapsho_3bbc63_idx",
            old_name="skill_bluep_snapsho_7a8335_idx",
        ),
        migrations.RenameIndex(
            model_name="rolelibrarysnapshot",
            new_name="skill_bluep_workspa_e78884_idx",
            old_name="skill_bluep_workspa_0efc61_idx",
        ),
        migrations.RenameIndex(
            model_name="rolelibrarysnapshot",
            new_name="skill_bluep_provide_6f53d7_idx",
            old_name="skill_bluep_provide_4f45e1_idx",
        ),
        migrations.AlterField(
            model_name="skillblueprintrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
