# Generated by Django 6.0.2 on 2026-03-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill_blueprint", "0005_stage4_blueprint_review_flow"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="skillblueprintrun",
            new_name="skill_bluep_workspa_9599b3_idx",
            old_name="skill_bluep_workspa_1b1d0e_idx",
        ),
    ]
