# Generated by Django 6.0.2 on 2026-03-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill_blueprint", "0007_stage5_clarifications_and_publish"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clarificationcycle",
            new_name="skill_bluep_workspa_70ae78_idx",
            old_name="skill_bluep_workspa_491deb_idx",
        ),
        migrations.RenameIndex(
            model_name="clarificationcycle",
            new_name="skill_bluep_workspa_683a7d_idx",
            old_name="skill_bluep_workspa_bf7ae0_idx",
        ),
        migrations.RenameIndex(
            model_name="clarificationquestion",
            new_name="skill_bluep_workspa_29ec84_idx",
            old_name="skill_bluep_workspa_ef0cca_idx",
        ),
        migrations.RenameIndex(
            model_name="clarificationquestion",
            new_name="skill_bluep_bluepri_e1d48a_idx",
            old_name="skill_bluep_bluepri_7eac9e_idx",
        ),
        migrations.RenameIndex(
            model_name="clarificationquestion",
            new_name="skill_bluep_cycle_i_76c946_idx",
            old_name="skill_bluep_cycle_i_4c8843_idx",
        ),
        migrations.RenameIndex(
            model_name="skillblueprintrun",
            new_name="skill_bluep_workspa_8dad65_idx",
            old_name="skill_bluep_workspa_95d730_idx",
        ),
    ]
