# Generated by Django 6.0.2 on 2026-04-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_context", "0019_roadmapanalysisrun"),
        (
            "skill_blueprint",
            "0008_rename_skill_bluep_workspa_491deb_idx_skill_bluep_workspa_70ae78_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skillblueprintrun",
            name="roadmap_analysis",
            field=models.ForeignKey(
                blank=True,
                help_text="The roadmap analysis that provided structured input for this blueprint.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blueprint_runs",
                to="org_context.roadmapanalysisrun",
            ),
        ),
    ]
