# Generated by Django 6.0.2 on 2026-04-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        ("org_context", "0021_backfill_planning_contexts"),
        ("skill_blueprint", "0009_skillblueprintrun_roadmap_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillblueprintrun",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this blueprint is scoped to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blueprint_runs",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="skillblueprintrun",
            index=models.Index(
                fields=["workspace", "planning_context"],
                name="skill_bluep_workspa_cd1188_idx",
            ),
        ),
    ]
