# Generated by Django 5.1.6 on 2026-03-19 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Unique human-readable identifier (e.g. "scheduler.cleanup_executions")', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='What this task does — shown in admin and future UI')),
                ('task_path', models.CharField(help_text='Dotted path to the Dramatiq actor (e.g. "scheduler.tasks.cleanup_old_executions")', max_length=255)),
                ('task_kwargs', models.JSONField(blank=True, default=dict, help_text='Keyword arguments passed to the actor')),
                ('queue', models.CharField(default='default', help_text='Dramatiq queue name', max_length=64)),
                ('schedule_type', models.CharField(choices=[('cron', 'Cron expression'), ('interval', 'Fixed interval (seconds)'), ('once', 'One-shot at specific time')], max_length=16)),
                ('cron_expression', models.CharField(blank=True, default='', help_text='5-field cron: "minute hour day month weekday" (only for cron type)', max_length=100)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds between runs (only for interval type)', null=True)),
                ('run_at', models.DateTimeField(blank=True, help_text='Exact time for one-shot tasks (only for once type)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive tasks are never dispatched')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='When the scheduler should next dispatch this task', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this task was last dispatched', null=True)),
                ('max_instances', models.PositiveSmallIntegerField(default=1, help_text='Max concurrent Dramatiq messages for this schedule')),
                ('misfire_grace_seconds', models.PositiveIntegerField(default=300, help_text='Skip dispatch if overdue by more than this many seconds')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive dispatch failures. Reset on success.')),
                ('auto_paused', models.BooleanField(default=False, help_text='True if the scheduler auto-paused this task after repeated failures. Re-activating via admin clears this flag.')),
                ('is_system', models.BooleanField(default=False, help_text='System tasks are seeded by code and cannot be deleted via API')),
                ('organization_uuid', models.UUIDField(blank=True, db_index=True, help_text='Null for system tasks; set for org-scoped schedules', null=True)),
                ('created_by_uuid', models.UUIDField(blank=True, help_text='User or LLM agent that created this schedule', null=True)),
                ('user_timezone', models.CharField(blank=True, default='UTC', help_text='IANA timezone for user-facing schedules (e.g. "America/New_York"). Cron expressions are evaluated in this timezone.', max_length=64)),
            ],
            options={
                'db_table': 'scheduler_task',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='scheduler_t_is_acti_1f818e_idx'), models.Index(fields=['organization_uuid', 'is_active'], name='scheduler_t_organiz_4368ad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'cron'), _negated=True), models.Q(('cron_expression', ''), _negated=True), _connector='OR'), name='sched_cron_requires_expression'), models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'interval'), _negated=True), ('interval_seconds__gte', 1), _connector='OR'), name='sched_interval_requires_seconds'), models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'once'), _negated=True), models.Q(('run_at__isnull', True), _negated=True), _connector='OR'), name='sched_once_requires_run_at'), models.CheckConstraint(condition=models.Q(('max_instances__gte', 1)), name='sched_max_instances_positive')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dispatched', 'Message dispatched to broker'), ('skipped', 'Skipped (misfire / concurrency)'), ('failed', 'Dispatch failed')], max_length=16)),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True, default='')),
                ('dramatiq_message_id', models.CharField(blank=True, default='', help_text='Dramatiq message ID for tracing', max_length=64)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.scheduledtask')),
            ],
            options={
                'db_table': 'scheduler_execution',
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['task', '-dispatched_at'], name='scheduler_e_task_id_5eb5af_idx')],
            },
        ),
    ]
