# Generated by Django 5.1.6 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='developmentplanrun',
            new_name='development_workspa_d155fc_idx',
            old_name='developmen_workspa_7b6323_idx',
        ),
        migrations.RenameIndex(
            model_name='developmentplanrun',
            new_name='development_scope_f7785b_idx',
            old_name='developmen_scope_0992dd_idx',
        ),
    ]
