# Generated by Django 6.0.2 on 2026-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0003_employee_and_status_updates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="developmentplanrun",
            new_name="development_workspa_74193f_idx",
            old_name="development_workspa_63eb2c_idx",
        ),
        migrations.AlterField(
            model_name="developmentplanrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
