# Generated by Django 6.0.2 on 2026-03-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0005_stage9_plan_lineage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="developmentplanrun",
            new_name="development_workspa_49fd4a_idx",
            old_name="developmen_worksp_9d8341_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanrun",
            new_name="development_workspa_b22038_idx",
            old_name="developmen_worksp_2fd08a_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanrun",
            new_name="development_workspa_7e09d5_idx",
            old_name="developmen_worksp_0677ba_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanrun",
            new_name="development_workspa_bc1bf6_idx",
            old_name="developmen_worksp_7150cf_idx",
        ),
    ]
