# Generated by Django 6.0.2 on 2026-03-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0007_stage10_plan_artifacts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="developmentplanartifact",
            new_name="development_workspa_e893f1_idx",
            old_name="developmen_workspa_95b0e1_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanartifact",
            new_name="development_workspa_8ea008_idx",
            old_name="developmen_workspa_43ab8d_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanartifact",
            new_name="development_workspa_dd26af_idx",
            old_name="developmen_workspa_1da1dc_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanartifact",
            new_name="development_plan_ru_a27309_idx",
            old_name="developmen_plan_ru_61d2f1_idx",
        ),
        migrations.RenameIndex(
            model_name="developmentplanartifact",
            new_name="development_workspa_362388_idx",
            old_name="developmen_workspa_4bf586_idx",
        ),
    ]
