# Generated by Django 6.0.2 on 2026-04-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        (
            "development_plans",
            "0008_rename_developmen_workspa_95b0e1_idx_development_workspa_e893f1_idx_and_more",
        ),
        (
            "evidence_matrix",
            "0006_rename_evidence_ma_workspa_a8ddce_idx_evidence_ma_workspa_d5d355_idx",
        ),
        ("org_context", "0020_planning_context"),
        ("skill_blueprint", "0009_skillblueprintrun_roadmap_analysis"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="developmentplanrun",
            name="development_plan_one_current_team_per_workspace",
        ),
        migrations.RemoveConstraint(
            model_name="developmentplanrun",
            name="development_plan_one_current_individual_per_workspace",
        ),
        migrations.AddField(
            model_name="developmentplanrun",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this plan is scoped to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="development_plan_runs",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="developmentplanrun",
            index=models.Index(
                fields=["workspace", "planning_context"],
                name="development_workspa_159ee8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="developmentplanrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("planning_context__isnull", True),
                    ("scope", "team"),
                ),
                fields=("workspace", "scope"),
                name="development_plan_one_current_team_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="developmentplanrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("planning_context__isnull", True),
                    ("scope", "individual"),
                ),
                fields=("workspace", "employee"),
                name="development_plan_one_current_individual_legacy",
            ),
        ),
        migrations.AddConstraint(
            model_name="developmentplanrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("planning_context__isnull", False),
                    ("scope", "team"),
                ),
                fields=("workspace", "planning_context", "scope"),
                name="development_plan_one_current_team_per_context",
            ),
        ),
        migrations.AddConstraint(
            model_name="developmentplanrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_current", True),
                    ("planning_context__isnull", False),
                    ("scope", "individual"),
                ),
                fields=("workspace", "planning_context", "employee"),
                name="development_plan_one_current_individual_per_context",
            ),
        ),
    ]
