# Generated by Django 5.1.6 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessmentcycle',
            new_name='employee_as_workspa_8583c4_idx',
            old_name='employee_ass_workspa_67f8ef_idx',
        ),
    ]
