# Generated by Django 6.0.2 on 2026-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_assessment", "0003_employeeassessmentpack"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="employeeassessmentpack",
            new_name="employee_as_cycle_i_6b5670_idx",
            old_name="employee_as_cycle_i_f75ca8_idx",
        ),
        migrations.RenameIndex(
            model_name="employeeassessmentpack",
            new_name="employee_as_employe_8f43db_idx",
            old_name="employee_as_employe_eb1661_idx",
        ),
        migrations.AlterField(
            model_name="assessmentcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
