# Generated by Django 6.0.2 on 2026-03-24 19:15

from django.db import migrations, models


def forwards_map_statuses(apps, schema_editor):
    AssessmentCycle = apps.get_model('employee_assessment', 'AssessmentCycle')
    EmployeeAssessmentPack = apps.get_model('employee_assessment', 'EmployeeAssessmentPack')

    AssessmentCycle.objects.filter(status='ready').update(status='generated')
    EmployeeAssessmentPack.objects.filter(status='ready').update(status='generated')
    EmployeeAssessmentPack.objects.filter(status='sent').update(status='opened')
    EmployeeAssessmentPack.objects.filter(status='answered').update(status='submitted')


def backwards_map_statuses(apps, schema_editor):
    AssessmentCycle = apps.get_model('employee_assessment', 'AssessmentCycle')
    EmployeeAssessmentPack = apps.get_model('employee_assessment', 'EmployeeAssessmentPack')

    AssessmentCycle.objects.filter(status='generated').update(status='ready')
    EmployeeAssessmentPack.objects.filter(status='generated').update(status='ready')
    EmployeeAssessmentPack.objects.filter(status='opened').update(status='sent')
    EmployeeAssessmentPack.objects.filter(status='submitted').update(status='answered')


class Migration(migrations.Migration):

    dependencies = [
        ('skill_blueprint', '0007_stage5_clarifications_and_publish'),
        ('employee_assessment', '0004_rename_employee_as_cycle_i_f75ca8_idx_employee_as_cycle_i_6b5670_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcycle',
            name='blueprint_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='assessment_cycles',
                to='skill_blueprint.skillblueprintrun',
            ),
        ),
        migrations.AddField(
            model_name='employeeassessmentpack',
            name='active_vector_generation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='employeeassessmentpack',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeassessmentpack',
            name='questionnaire_version',
            field=models.CharField(blank=True, default='stage7-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='employeeassessmentpack',
            name='selection_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeeassessmentpack',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentcycle',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('generated', 'Generated'),
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('superseded', 'Superseded'),
                ],
                default='draft',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='employeeassessmentpack',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('generated', 'Generated'),
                    ('opened', 'Opened'),
                    ('submitted', 'Submitted'),
                    ('completed', 'Completed'),
                    ('superseded', 'Superseded'),
                ],
                default='generated',
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name='assessmentcycle',
            index=models.Index(fields=['workspace', 'blueprint_run'], name='employee_as_workspa_8609df_idx'),
        ),
        migrations.RunPython(forwards_map_statuses, backwards_map_statuses),
    ]

