# Generated by Django 6.0.2 on 2026-03-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_assessment", "0005_stage7_assessment_workflow"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assessmentcycle",
            new_name="employee_as_workspa_7c6980_idx",
            old_name="employee_as_workspa_8609df_idx",
        ),
    ]
