# Generated by Django 6.0.2 on 2026-04-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_intake", "0008_intakeworkspace_organization"),
        (
            "employee_assessment",
            "0006_rename_employee_as_workspa_8609df_idx_employee_as_workspa_7c6980_idx",
        ),
        ("org_context", "0020_planning_context"),
        ("skill_blueprint", "0009_skillblueprintrun_roadmap_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentcycle",
            name="planning_context",
            field=models.ForeignKey(
                blank=True,
                help_text="Planning context this assessment cycle is scoped to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_cycles",
                to="org_context.planningcontext",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentcycle",
            index=models.Index(
                fields=["workspace", "planning_context"],
                name="employee_as_workspa_03b6fe_idx",
            ),
        ),
    ]
